from dotenv import load_dotenv
from langchain_chroma import Chroma
from langchain_google_genai import GoogleGenerativeAIEmbeddings

load_dotenv()

embeddings = GoogleGenerativeAIEmbeddings(
    model="models/gemini-embedding-001"
)

db = Chroma(
    persist_directory="day-04/chroma_db",
    embedding_function=embeddings
)
retriever = db.as_retriever(
    search_kwargs={"k": 3}
)
question = "What are the steps to hotlist a debit card?"

# question invoked  to retriver method to get the relevant documents from the Chroma database. The retriever will return the top 3 documents that are most relevant to the question based on the embeddings generated by the Google Generative AI model.

docs = retriever.invoke(question)
print("Chroma DB loaded successfully")

print("\nRetrieved documents:")

for doc in docs:
    print("--------------------------------")
    print("Source:", doc.metadata.get("source"))
    print(doc.page_content)